# config/xml/User.dcm.yml
EAS\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  oneToMany:
    reportedBugs:
      targetEntity: EAS\Bug
      mappedBy: reporter
    assignedBugs:
      targetEntity: EAS\Bug
      mappedBy: engineer