# config/yaml/Bug.dcm.yml
EAS\Bug:
  type: entity
  table: bugs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    description:
      type: text
    created:
      type: datetime
    status:
      type: string
  manyToOne:
    reporter:
      targetEntity: EAS\User
      inversedBy: reportedBugs
    engineer:
      targetEntity: EAS\User
      inversedBy: assignedBugs
  manyToMany:
    products:
      targetEntity: EAS\Product
  lifecycleCallbacks:
    prePersist: [prePersist]